@startuml
title "学生エンティティと講義エンティティ(関連実体あり)"

entity "学生" as student #faa {
    学生コード
    --
    学生名
}

entity "受講" as attendance #aaf {
    学生コード(FK)
    講義コード(FK)
    --
}

entity "講義" as lecture #faa {
    講義コード
    --
    講義名
}

student }|.|| attendance
attendance }|.|| lecture
@enduml